<!doctype html>
<html>
    <head>
        <title>Adição Resultado</title>
        <style>
            .aceito{
                color:green;
            }
            .naoaceito{
                color:red;
            }
        </style>
    </head>  
    <body>
        <center><?php
            $num=$_POST['num1'];
            $num2=$_POST['num2'];
            $num3=$_POST['num3'];
            $num4=$_POST['num4'];
            $num5=$_POST['num5'];
            $num6=$_POST['num6'];
            $num7=$_POST['num7'];
            $num8=$_POST['num8'];
            $num9=$_POST['num9'];
            $num10=$_POST['num10'];
            $num11=$_POST['num11'];
            $num12=$_POST['num12'];
            $num13=$_POST['num13'];
            $num14=$_POST['num14'];
            $num15=$_POST['num15'];
            $num16=$_POST['num16'];
            $num17=$_POST['num17'];
            $num18=$_POST['num18'];
            $num19=$_POST['num19'];
            $num20=$_POST['num20'];
            $total=0;
            $negativos=0;
            if($num>=0){
                $total=$total+$num;
            }
            else{$negativos==$negativos+1}
            if($num2>=0){
                $total=$total+$num2;
            }
            else{$negativos==$negativos+1}
            if($num3>=0){
                $total=$total+$num3;
            }
            else{$negativos==$negativos+1}
            if($num4>=0){
                $total=$total+$num4;
            }
            else{$negativos==$negativos+1}
            if($num5>=0){
                $total=$total+$num5;
            }
            else{$negativos==$negativos+1}
            if($num6>=0){
                $total=$total+$num6;
            }
            else{$negativos==$negativos+1}
            if($num7>=0){
                $total=$total+$num7;
            }
            else{$negativos==$negativos+1}
            if($num8>=0){
                $total=$total+$num8;
            }
            else{$negativos==$negativos+1}
            if($num9>=0){
                $total=$total+$num9;
            }
            else{$negativos==$negativos+1}
            if($num10>=0){
                $total=$total+$num10;
            }
            else{$negativos==$negativos+1}
            if($num11>=0){
                $total=$total+$num11;
            }
            else{$negativos==$negativos+1}
            if($num12>=0){
                $total=$total+$num12;
            }
            else{$negativos==$negativos+1}
            if($num13>=0){
                $total=$total+$num13;
            }
            else{$negativos==$negativos+1}
            if($num14>=0){
                $total=$total+$num14;
            }
            else{$negativos==$negativos+1}
            if($num15>=0){
                $total=$total+$num15;
            }
            else{$negativos==$negativos+1}
            if($num16>=0){
                $total=$total+$num16;
            }
            else{$negativos==$negativos+1}
            if($num17>=0){
                $total=$total+$num17;
            }
            else{$negativos==$negativos+1}
            if($num18>=0){
                $total=$total+$num18;
            }
            else{$negativos==$negativos+1}
            if($num19>=0){
                $total=$total+$num19;
            }
            else{$negativos==$negativos+1}
            if($num20>=0){
                $total=$total+$num20;
            }
            else{$negativos==$negativos+1}
        ?></center>
    </body>
</html>